"""What counts as a crime, and — the whole point — *whose* crime it is.

**There is no universal law in the Verge, and this file does not invent one.**
The survey that prompted it found no court, no warrant, no arrest and no
bounty on the player anywhere in the game: every "legal" act was a reputation
delta, a memory entry, a percentage skimmed at a till, or an escalation ladder
bolted to a berth. The temptation was to answer that with a police force. That
would have been the wrong game — `data/factions.py` says plainly that the
Charter "fields no armed vessel anywhere", and a sector-wide constabulary is
exactly the "single authority that could weaponise the reproduction licence"
that the programme's own charter was written to prevent.

So each power's law is real, and each is only as real as that power's reach.
An offence is charged **under somebody's writ**, in a place where somebody was
looking, by an institution that has to be able to find you afterwards. Operate
where a power has no hulls, no quay and no register and you are not innocent —
you are simply unobserved, which is a different thing and is allowed to feel
different.

`powers` is the heart of the table. Trespass offends everyone because everyone
keeps a register. Unlicensed germination is a crime *only* under the Charter,
because the licence is the Charter's whole reason to exist and the Freeholds
post a price for unlicensed seed on the open market. A captain who never
carries seed and never settles ground can commit almost nothing; one who runs
wildseed into Charter space is committing the gravest thing in the table every
time they dock.

`prescribes` is the other half of the bargain. An act nobody filed on becomes
uncharg­eable after this many days — the reason a chronicle does not accumulate
an unpayable backlog from its first bad decade, and the reason lying low is a
strategy rather than a way of postponing the inevitable. The two acts that
never prescribe are the two the powers keep permanent registers of.
"""

from __future__ import annotations

from dataclasses import dataclass

#: Every power that keeps a law. The Abyssals have no register and the Bloom
#: has no opinion, so neither can charge you with anything.
LAWFUL = ("charter", "concordat", "freeholds", "sanhedrin")

#: Long enough to be worth outrunning, short enough that a decade of small
#: sins does not become a life sentence. Used where an offence prescribes at
#: the ordinary rate.
ORDINARY = 540.0

#: Acts a power keeps on the permanent register. `-1` never prescribes.
NEVER = -1.0


@dataclass(frozen=True)
class Offence:
    """One thing a power will charge you with, in that power's own words."""

    id: str
    name: str
    #: The words a charge is laid in. Every screen quotes this rather than
    #: inventing its own phrasing, so the docket, the summons and the verdict
    #: cannot describe the same act three ways.
    writ: str
    #: 0..1. Scales the assessment, the sanction, and how hard a power tries.
    gravity: float
    #: Which powers treat this as an offence *at all*. The Freeholds are
    #: absent from most of it on purpose: they are the market where an
    #: unlicensed seed has a posted price, and a power cannot charge you with
    #: the thing it sells.
    powers: tuple[str, ...]
    #: Days before an unfiled act can no longer be charged. `NEVER` for the
    #: two things that stay on the register.
    prescribes: float = ORDINARY
    #: Whether the forum will let you buy your way out before a verdict.
    settleable: bool = True
    #: What the player did, in the second person, for the log and the docket.
    did: str = ""
    #: **Generated by the process rather than by the captain.** These two are
    #: how the layer stops being escapable by never going home — and they are
    #: also how it very nearly ate itself. A default charge decided in absence
    #: generates a default charge; the debt it creates goes unpaid and
    #: generates arrears; that is decided in absence too. Measured from a
    #: single contraband bust: 61,820 charges and ₡498 million owed inside
    #: eight years, which is a save file that will not load rather than a
    #: game. A power has *one* "you are not answering us" at a time — see
    #: `dockets.PROCEDURAL_DAYS`. What escalates is the instrument, through
    #: `tribunal.severity`'s count of priors, not the paperwork.
    procedural: bool = False


OFFENCES: list[Offence] = [
    # ── the containment regime ─────────────────────────────────────────────
    Offence(
        "unlicensed", "Unlicensed germination",
        "germination of reproductive stock without authorisation",
        0.95, ("charter",), NEVER, settleable=False,
        did="you put seed in the ground without a licence"),
    Offence(
        "contraband", "Carriage",
        "carriage of proscribed material",
        0.55, ("charter", "concordat"),
        did="you were found carrying what they proscribe"),
    Offence(
        "trafficking", "Trafficking",
        "disposal of proscribed material off the register",
        0.70, ("charter", "concordat", "sanhedrin"),
        did="you sold off the books"),

    # ── violence ───────────────────────────────────────────────────────────
    Offence(
        "killing", "Destruction of a hull",
        "destruction of a registered hull and its complement",
        1.00, LAWFUL, NEVER, settleable=False,
        did="you destroyed a hull on their register"),
    Offence(
        "affray", "Affray",
        "discharge of weapons within a controlled volume",
        0.45, ("charter", "concordat", "sanhedrin"),
        did="you opened fire inside their approaches"),

    # ── the quay and the ring ──────────────────────────────────────────────
    Offence(
        "forcing", "Forced berth",
        "entry to a structure against refusal",
        0.60, ("charter", "concordat", "sanhedrin"),
        did="you cut in against a refusal"),
    Offence(
        "evasion", "Evasion",
        "passage of a warded ring without clearance",
        0.40, ("concordat", "charter"),
        did="you ran a picket"),

    # ── ground ─────────────────────────────────────────────────────────────
    Offence(
        "trespass", "Trespass",
        "settlement of ground standing on another's register",
        0.50, LAWFUL,
        did="you settled ground they had registered"),
    Offence(
        "defiance", "Defiance of a levy",
        "refusal of a levy lawfully raised",
        0.65, LAWFUL,
        did="you refused their levy to their face"),

    # ── the law about the law ──────────────────────────────────────────────
    # Both are generated *by* the process rather than by anything the captain
    # does out in the dark, which is what stops the system being escapable by
    # simply never going home. A power that cannot prove you carried anything
    # can always prove you did not turn up.
    Offence(
        "arrears", "Arrears",
        "a judgment debt left unanswered",
        0.50, LAWFUL, NEVER, settleable=True, procedural=True,
        did="you let a judgment stand unpaid"),
    Offence(
        "default", "Failure to answer",
        "failure to answer a summons lawfully served",
        0.55, LAWFUL, NEVER, settleable=True, procedural=True,
        did="you did not answer the summons"),
]

OFFENCES_BY_ID: dict[str, Offence] = {o.id: o for o in OFFENCES}


def charges_it(offence_id: str, power: str) -> bool:
    """Does this power treat this act as an offence at all?

    **The one door.** Asked by `sim/dockets.allege` before anything is
    recorded, so a power cannot end up prosecuting something its own table
    says it does not recognise — and so the Freeholds' whole character (no
    position on anything except margin) is expressed as data rather than as a
    special case somewhere in the sim.
    """
    offence = OFFENCES_BY_ID.get(offence_id)
    return bool(offence) and power in offence.powers


def under(power: str) -> list[Offence]:
    """Everything this power will charge, for the manual and the law screen."""
    return [o for o in OFFENCES if power in o.powers]
