"""Every suite in the harness, and the module that holds it.

`__main__.py` carried a five-line `if "name" in wanted:` block per suite, and
grew by one every time a cycle added a check file — past five hundred lines,
which is the point at which this project splits a file. The blocks were all
the same block, so they are a table now: adding a suite is one row.

`optional` marks the four that need PyQt. They are skipped with a note rather
than failing the run, so the suite is usable on a machine without it.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class SuiteSpec:
    key: str          # what you type on the command line
    module: str       # the module under `seedfall.tests`
    label: str        # what the report calls it
    optional: bool = False   # skip, with a note, if PyQt is missing


SUITES: list[SuiteSpec] = [
    SuiteSpec("sim", "test_sim", "simulation"),
    SuiteSpec("solvency", "test_solvency", "money cannot be conjured"),
    SuiteSpec("prize", "test_prize", "striking colours"),
    SuiteSpec("despatch", "test_despatch", "the despatch board"),
    SuiteSpec("xeno", "test_xeno", "xenotech"),
    SuiteSpec("play", "test_play", "playability"),
    SuiteSpec("endgame", "test_endgame", "the Bloom endgame"),
    SuiteSpec("combat", "test_combat", "tactical"),
    SuiteSpec("flight", "test_flight", "flight"),
    SuiteSpec("empire", "test_empire", "empire"),
    SuiteSpec("crew", "test_crew", "crew"),
    SuiteSpec("missions", "test_missions", "missions"),
    SuiteSpec("explore", "test_explore", "exploration"),
    SuiteSpec("provenance", "test_provenance", "provenance"),
    SuiteSpec("options", "test_options", "options"),
    SuiteSpec("mesh", "test_mesh", "mesh"),
    SuiteSpec("biology", "test_biology", "biology"),
    SuiteSpec("settlement", "test_settlement", "settlement"),
    SuiteSpec("mining", "test_mining", "mining"),
    SuiteSpec("research", "test_research", "research"),
    SuiteSpec("trade", "test_trade", "trade"),
    SuiteSpec("ground", "test_ground", "ground"),
    SuiteSpec("politics", "test_politics", "politics"),
    SuiteSpec("design", "test_design", "design"),
    SuiteSpec("orders", "test_orders", "orders"),
    SuiteSpec("assessment", "test_assessment", "assessment"),
    SuiteSpec("balance", "test_balance", "balance"),
    SuiteSpec("bloom", "test_bloom_arc", "bloom"),
    SuiteSpec("reachable", "test_reachable", "reachable"),
    SuiteSpec("efficacy", "test_efficacy", "efficacy"),
    SuiteSpec("transit", "test_transit", "transit"),
    SuiteSpec("watches", "test_watches", "watches"),
    SuiteSpec("courtship", "test_courtship", "courtship"),
    SuiteSpec("routing", "test_routing", "routing"),
    SuiteSpec("magazine", "test_magazine", "magazine"),
    SuiteSpec("stranded", "test_stranded", "stranded"),
    SuiteSpec("geography", "test_geography", "geography"),
    SuiteSpec("prospect", "test_prospect", "prospect"),
    SuiteSpec("gates", "test_gates", "gates"),
    SuiteSpec("docking", "test_docking", "docking"),
    SuiteSpec("impulse", "test_impulse", "impulse"),
    SuiteSpec("knock", "test_knock", "knock"),
    SuiteSpec("moorings", "test_moorings", "moorings"),
    SuiteSpec("clearance", "test_clearance", "clearance"),
    SuiteSpec("standoff", "test_standoff", "standoff berths"),
    SuiteSpec("freeflight", "test_freeflight", "free flight"),
    SuiteSpec("byhand", "test_byhand", "flying by hand"),
    SuiteSpec("showflying", "test_showflying", "showing the flying"),
    SuiteSpec("fog", "test_fog", "fog"),
    SuiteSpec("conn", "test_conn", "conn"),
    SuiteSpec("shock", "test_shock", "what a contact looks like"),
    SuiteSpec("turret", "test_turret", "a gun with hands on it"),
    SuiteSpec("uwp", "test_uwp", "the world profile"),
    SuiteSpec("lifepath", "test_lifepath", "two dice and a life lived"),
    SuiteSpec("shore", "test_shore", "people, possessions and the concourse"),
    SuiteSpec("muster", "test_muster", "the crew, whole"),
    SuiteSpec("concourse", "test_concourse", "places, and what they sell"),
    SuiteSpec("bodywork", "test_bodywork", "bodies, berths and faces"),
    SuiteSpec("kindred", "test_kindred", "what a crew is made of"),
    SuiteSpec("plotting", "test_plotting", "plotting against moving things"),
    SuiteSpec("position", "test_position", "ship position"),
    SuiteSpec("cameras", "test_cameras", "cameras"),
    SuiteSpec("reticle", "test_reticle", "reticle"),
    SuiteSpec("connwindow", "test_connwindow", "conn window"),
    SuiteSpec("worlds", "test_worlds", "worlds"),
    SuiteSpec("surfaces", "test_surfaces", "surfaces"),
    SuiteSpec("projection", "test_projection", "projection"),
    SuiteSpec("drawbudget", "test_drawbudget", "draw budget"),
    SuiteSpec("starlight", "test_starlight", "starlight"),
    SuiteSpec("hullshapes", "test_hullshapes", "hull shapes"),
    SuiteSpec("catalogue", "test_catalogue", "catalogue"),
    SuiteSpec("silhouettes", "test_silhouettes", "silhouettes"),
    SuiteSpec("works3d", "test_works3d", "station structures"),
    SuiteSpec("robots", "test_robots", "machines"),
    SuiteSpec("unattended", "test_unattended", "machines nobody is watching"),
    SuiteSpec("robots3d", "test_robots3d", "machine bodies"),
    SuiteSpec("bay", "test_bay", "internal bays"),
    SuiteSpec("control", "test_control", "approach control"),
    SuiteSpec("boats", "test_boats", "what clearance buys"),
    SuiteSpec("forcing", "test_forcing", "forcing a berth"),
    SuiteSpec("interdiction", "test_interdiction", "interdiction"),
    SuiteSpec("fleets", "test_fleets", "order of battle"),
    SuiteSpec("piracy", "test_piracy", "piracy"),
    SuiteSpec("fence", "test_fence", "the fence"),
    SuiteSpec("feedstock", "test_feedstock", "feedstock"),
    SuiteSpec("ticks", "test_ticks", "tick shapes"),
    SuiteSpec("swarm", "test_swarm", "machines on guard"),
    SuiteSpec("life3d", "test_life3d", "xenoform bodies"),
    SuiteSpec("parts3d", "test_parts3d", "fitting pictures"),
    SuiteSpec("relics3d", "test_relics3d", "relic pictures"),
    SuiteSpec("skykit", "test_sky_kit", "sky kit"),
    SuiteSpec("lighting", "test_lighting", "lighting"),
    SuiteSpec("orbits", "test_orbits", "orbits"),
    SuiteSpec("orbitheight", "test_orbit_height", "the height of an orbit"),
    SuiteSpec("programmes", "test_programmes", "programmes"),
    SuiteSpec("exchequer", "test_exchequer", "exchequer"),
    SuiteSpec("industry", "test_industry", "industry"),
    SuiteSpec("licences", "test_licences", "licences"),
    SuiteSpec("declared", "test_declared", "declared"),
    SuiteSpec("revived", "test_revived", "revived"),
    SuiteSpec("screening", "test_screening", "screening"),
    SuiteSpec("lopsided", "test_lopsided", "lopsided"),
    SuiteSpec("pilot", "test_pilot", "pilot"),
    SuiteSpec("berthing", "test_berthing", "berthing"),
    SuiteSpec("thrusters", "test_thrusters", "thrusters"),
    SuiteSpec("weave", "test_weave", "weave"),
    SuiteSpec("hail", "test_hail", "the channel"),
    SuiteSpec("customs", "test_customs", "customs"),
    SuiteSpec("allegiance", "test_allegiance", "allegiance"),
    SuiteSpec("public", "test_public", "public"),
    SuiteSpec("territory", "test_territory", "territory"),
    SuiteSpec("charts", "test_charts", "charts"),
    SuiteSpec("aftermath", "test_aftermath", "aftermath"),
    SuiteSpec("notes", "test_notes", "notes"),
    SuiteSpec("layers", "test_layers", "layers"),
    SuiteSpec("cargo", "test_cargo", "cargo"),
    SuiteSpec("freight", "test_freight", "freight"),
    SuiteSpec("workings", "test_workings", "workings"),
    SuiteSpec("burns", "test_burns", "burns"),
    SuiteSpec("bench", "test_bench", "bench"),
    SuiteSpec("works", "test_works", "works"),
    SuiteSpec("overtures", "test_overtures", "overtures"),
    SuiteSpec("seats", "test_seats", "seats"),
    SuiteSpec("founding", "test_founding", "founding"),
    SuiteSpec("attempts", "test_attempts", "attempts"),
    SuiteSpec("reach", "test_reach", "reach"),
    SuiteSpec("plans", "test_plans", "plans"),
    SuiteSpec("beginnings", "test_beginnings", "beginnings"),
    SuiteSpec("legacy", "test_legacy", "legacy"),
    SuiteSpec("instruments", "test_instruments", "instruments"),
    SuiteSpec("voices", "test_voices", "voices"),
    SuiteSpec("bridge", "test_bridge_protocol", "the bridge protocol and socket"),
    SuiteSpec("time", "test_time", "time"),
    SuiteSpec("anchorage", "test_anchorage", "anchorage"),
    SuiteSpec("traffic", "test_traffic", "traffic"),
    SuiteSpec("doctrine", "test_doctrine", "doctrine"),
    SuiteSpec("firing", "test_firing", "firing"),
    SuiteSpec("approach", "test_approach", "approach"),
    SuiteSpec("officials", "test_officials", "officials"),
    SuiteSpec("dormancy", "test_dormancy", "dormancy"),
    SuiteSpec("tuning", "test_tuning", "tuning"),
    SuiteSpec("hands", "test_hands", "hands"),
    SuiteSpec("approaching", "test_approach_game", "approaching"),
    SuiteSpec("harness", "test_harness_guard", "harness"),
    SuiteSpec("salvage", "test_salvage", "salvage"),
    SuiteSpec("provisional", "test_provisional", "provisional"),
    SuiteSpec("counter", "test_counter", "counter"),
    SuiteSpec("wharfage", "test_wharfage", "wharfage"),
    SuiteSpec("climbs", "test_climbs", "climbs"),
    SuiteSpec("company", "test_company", "company"),
    SuiteSpec("parley", "test_parley", "parley"),
    SuiteSpec("wayhome", "test_wayhome", "wayhome"),
    SuiteSpec("abilities", "test_abilities", "abilities"),
    SuiteSpec("levy", "test_levy", "levy"),
    SuiteSpec("accord", "test_accord", "accord"),
    SuiteSpec("landing", "test_landing", "landing"),
    SuiteSpec("setdown", "test_setdown", "coming down"),
    SuiteSpec("charting", "test_charting", "charting"),
    SuiteSpec("conviction", "test_conviction", "conviction"),
    SuiteSpec("evidence", "test_bench_kinds", "evidence"),
    SuiteSpec("envoy", "test_envoy", "envoy"),
    SuiteSpec("seatwork", "test_seatwork", "seatwork"),
    SuiteSpec("thermal_doors", "test_thermal_doors", "thermal doors"),
    SuiteSpec("ventures", "test_ventures", "ventures"),
    SuiteSpec("orderplan", "test_orderplan", "order plan"),
    SuiteSpec("turnplan", "test_turnplan", "turn plan"),
    SuiteSpec("postings", "test_postings", "postings"),
    SuiteSpec("grants", "test_grants", "grants"),
    SuiteSpec("helm", "test_helm", "helm"),
    SuiteSpec("thermal", "test_thermal", "thermal"),
    SuiteSpec("courting", "test_courting", "courting"),
    SuiteSpec("law", "test_law", "law"),
    SuiteSpec("tribunal", "test_tribunal", "tribunal"),
    SuiteSpec("picture", "test_picture", "picture"),
    SuiteSpec("seams", "test_seams", "seams"),
    SuiteSpec("manual", "test_manual", "manual"),
    SuiteSpec("tutorial", "test_tutorial", "tutorial"),
    SuiteSpec("grudges", "test_grudges", "grudges"),
    SuiteSpec("gunnery", "test_gunnery", "gunnery"),
    SuiteSpec("volley", "test_volley", "volley"),
    SuiteSpec("gunboard", "test_gunboard", "gunboard"),
    SuiteSpec("readiness", "test_readiness", "readiness"),
    SuiteSpec("gunfire", "test_gunfire", "gunfire"),
    SuiteSpec("surveys", "test_surveys", "surveys"),
    SuiteSpec("chronicle", "test_chronicle", "chronicle", True),
    SuiteSpec("dig", "test_dig", "dig"),
    SuiteSpec("resume", "test_resume", "resume", True),
    SuiteSpec("verbs", "test_verbs", "verbs", True),
    SuiteSpec("war", "test_war", "war"),
    SuiteSpec("armada", "test_armada", "fleet actions"),
    SuiteSpec("engage", "test_engage", "opening fire"),
    SuiteSpec("savefile", "test_savefile", "save file"),
    SuiteSpec("ui", "test_ui", "interface", True),
    SuiteSpec("window", "test_window", "the window itself", True),
    SuiteSpec("flightpix", "test_flightpix", "the flying windows as pictures", True),
    SuiteSpec("orrery", "test_orrery", "orrery", True),
    SuiteSpec("pilotscreen", "test_pilot_screen", "pilot screen", True),
    SuiteSpec("flightdeck", "test_flightdeck", "one flight deck", True),
    SuiteSpec("flightops", "test_flightops", "flying the operations", True),
    SuiteSpec("collision", "test_collision", "collision guard", True),
    SuiteSpec("detection", "test_detection", "detection", True),
    SuiteSpec("elements", "test_elements", "orbital elements", True),
    SuiteSpec("remnants", "test_remnants", "stellar remnants"),
    SuiteSpec("gatetraffic", "test_gatetraffic", "gate traffic"),
    SuiteSpec("comms", "test_comms", "communications"),
    SuiteSpec("freeframe", "test_freeframe", "free-flight frame", True),
    SuiteSpec("bridgescreen", "test_bridge", "the bridge screen", True),
    SuiteSpec("bridgemarks", "test_bridge_marks", "bridge marks", True),
    SuiteSpec("sights", "test_sights", "sights", True),
    SuiteSpec("tripwire", "test_tripwire", "the sweep itself"),
    SuiteSpec("length", "test_length", "file length"),
    SuiteSpec("firecontrol", "test_firecontrol", "fire control", True),
    SuiteSpec("hostiles", "test_hostiles", "the captain's enemies"),
    SuiteSpec("persistence", "test_persistence", "a chronicle survives a restart"),
    SuiteSpec("screenkeys", "test_screenkeys", "every screen key, pressed", True),
    SuiteSpec("llmguard", "test_llm_guard", "a model cannot hang or crash the game"),
    SuiteSpec("bridgeguard", "test_bridge_guard", "the bridge refuses what it must"),
    SuiteSpec("engineguard", "test_engine_guard", "one clock, honest memos, loud excepts"),
    SuiteSpec("popouts", "test_popouts", "a pop-out closed is freed", True),
    SuiteSpec("flightsame", "test_flightsame",
              "the flying windows agree, and fly once a beat", True),
    SuiteSpec("slots", "test_slots", "named chronicles", True),
    SuiteSpec("cli", "test_cli", "the command line and the launcher"),
    SuiteSpec("uirules", "test_uirules", "the rules the screens used to hold"),
    SuiteSpec("fit", "test_fit", "the screens fit the window", True),
    SuiteSpec("keyboard", "test_keyboard", "played by the keyboard", True),
    SuiteSpec("exploits", "test_exploits", "the play-test's exploits, closed"),
    SuiteSpec("rulebook", "test_rulebook", "the rules the review found bent"),
    SuiteSpec("audio", "test_audio", "the soundscape, made and played", True),
    SuiteSpec("soundmap", "test_soundmap", "the right cue at the right moment",
              True),
    SuiteSpec("nemeses", "test_nemeses", "nemeses and the hunt"),
    SuiteSpec("nemesesui", "test_nemeses_ui", "the hunt, on the screens", True),
    SuiteSpec("freightlines", "test_freightlines",
              "a trading house earns only what the counters pay it"),
    SuiteSpec("adaptation", "test_adaptation", "the living hull"),
    SuiteSpec("reaches", "test_reaches", "the Far Reaches"),
    # Innovation 6: the Assembly.
    SuiteSpec("assembly", "test_assembly", "the Assembly sits, votes and binds"),
    # Innovation 2: the Kith.
    SuiteSpec("kith", "test_kith", "the Kith: contact and the lexicon"),
    SuiteSpec("kithgift", "test_kith_gift", "the Kith's gift economy"),
    SuiteSpec("arcs", "test_arcs", "officer arcs: every story lived"),
    # Innovation 9: renown, counsel, the memoir and the Hall.
    SuiteSpec("renown", "test_renown", "renown, counsel and the memoir"),
    SuiteSpec("renownui", "test_renown_ui", "the Voyage and the counsel, drawn",
              True),
    # Innovation 7: the living sky.
    SuiteSpec("phenomena", "test_phenomena", "the living sky"),
    SuiteSpec("skybodies", "test_skybodies",
              "comets, rogues and the nova come and go cleanly"),
    SuiteSpec("phenomenaui", "test_phenomena_ui", "the sky, on the screens",
              True),
    # Afoot: the Verge at walking pace (reviews/2026-09-21/afoot.md).
    SuiteSpec("afoot", "test_afoot", "afoot: the ground and the rules"),
    SuiteSpec("afootplay", "test_afoot_play",
              "afoot, played: finished, kept, and answered for"),
    SuiteSpec("afootui", "test_afoot_ui", "afoot, on the screen", True),
    SuiteSpec("afootshapes", "test_afoot_shapes",
              "afoot, drawn to shape: every hull and holding, all of it"),
    SuiteSpec("afootweight", "test_afoot_weight",
              "afoot's weight: spun, weightless, or a world's own"),
    SuiteSpec("afootfair", "test_afoot_fair",
              "afoot keeps faith: nothing rolled twice, nobody left to die"),
    SuiteSpec("afootcareer", "test_afoot_career",
              "afoot in a career: counsel, lessons, renown, and trouble"),
    SuiteSpec("afootfire", "test_afoot_fire",
              "afoot's fire: bursts, suppression, grenades and smoke"),
    SuiteSpec("craft", "test_craft",
              "single-seat craft: the cradle, the ticket, the sortie"),
    SuiteSpec("skycompany", "test_sky_company",
              "each hull in the other's sky: the launch and the ship"),
    SuiteSpec("camps", "test_camps",
              "what a landing party pitches when it means to stay"),
    SuiteSpec("vehicles", "test_vehicles",
              "what a landing party crosses ground in"),
    SuiteSpec("descent", "test_descent",
              "putting a party on a world: the lander and what she carries"),
    SuiteSpec("quayside", "test_quayside",
              "where you may deal from, and what the distance costs"),
    SuiteSpec("hangar", "test_hangar",
              "the hangar deck: cradles, buying, mending and selling craft"),
    SuiteSpec("craftbattle", "test_craft_battle",
              "a craft in an engagement: the run, the answer, the cradle"),
    SuiteSpec("craftui", "test_craft_ui",
              "the cradle and the cockpit, on the screen", True),
    SuiteSpec("berths", "test_berths",
              "berths: every shape flown alongside, towed, or refused"),
    SuiteSpec("crossing", "test_crossing",
              "made fast, or across: the berth, the boat, the shuttle, the "
              "line"),
    SuiteSpec("establishments", "test_establishments",
              "establishments: yards, hotels, wheels and dens, found and "
              "walked"),
    SuiteSpec("exports", "test_exports", "every module.name read exists"),
    SuiteSpec("maps", "test_maps", "the package maps name every module"),
]

SUITES_BY_KEY = {s.key: s for s in SUITES}

#: Order matters: this is the order a full run reports in.
ALL_SUITES = [s.key for s in SUITES]
