"""Every suite in the harness, and the module that holds it.

`__main__.py` carried a five-line `if "name" in wanted:` block per suite, and
grew by one every time a cycle added a check file — past five hundred lines,
which is the point at which this project splits a file. The blocks were all
the same block, so they are a table now: adding a suite is one row.

`optional` marks the four that need PyQt. They are skipped with a note rather
than failing the run, so the suite is usable on a machine without it.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class SuiteSpec:
    key: str          # what you type on the command line
    module: str       # the module under `seedfall.tests`
    label: str        # what the report calls it
    optional: bool = False   # skip, with a note, if PyQt is missing


SUITES: list[SuiteSpec] = [
    SuiteSpec("sim", "test_sim", "simulation"),
    SuiteSpec("xeno", "test_xeno", "xenotech"),
    SuiteSpec("play", "test_play", "playability"),
    SuiteSpec("combat", "test_combat", "tactical"),
    SuiteSpec("flight", "test_flight", "flight"),
    SuiteSpec("empire", "test_empire", "empire"),
    SuiteSpec("crew", "test_crew", "crew"),
    SuiteSpec("missions", "test_missions", "missions"),
    SuiteSpec("explore", "test_explore", "exploration"),
    SuiteSpec("provenance", "test_provenance", "provenance"),
    SuiteSpec("options", "test_options", "options"),
    SuiteSpec("mesh", "test_mesh", "mesh"),
    SuiteSpec("biology", "test_biology", "biology"),
    SuiteSpec("settlement", "test_settlement", "settlement"),
    SuiteSpec("mining", "test_mining", "mining"),
    SuiteSpec("research", "test_research", "research"),
    SuiteSpec("trade", "test_trade", "trade"),
    SuiteSpec("ground", "test_ground", "ground"),
    SuiteSpec("politics", "test_politics", "politics"),
    SuiteSpec("design", "test_design", "design"),
    SuiteSpec("orders", "test_orders", "orders"),
    SuiteSpec("assessment", "test_assessment", "assessment"),
    SuiteSpec("balance", "test_balance", "balance"),
    SuiteSpec("bloom", "test_bloom_arc", "bloom"),
    SuiteSpec("reachable", "test_reachable", "reachable"),
    SuiteSpec("efficacy", "test_efficacy", "efficacy"),
    SuiteSpec("transit", "test_transit", "transit"),
    SuiteSpec("watches", "test_watches", "watches"),
    SuiteSpec("courtship", "test_courtship", "courtship"),
    SuiteSpec("routing", "test_routing", "routing"),
    SuiteSpec("magazine", "test_magazine", "magazine"),
    SuiteSpec("stranded", "test_stranded", "stranded"),
    SuiteSpec("geography", "test_geography", "geography"),
    SuiteSpec("prospect", "test_prospect", "prospect"),
    SuiteSpec("gates", "test_gates", "gates"),
    SuiteSpec("docking", "test_docking", "docking"),
    SuiteSpec("impulse", "test_impulse", "impulse"),
    SuiteSpec("knock", "test_knock", "knock"),
    SuiteSpec("moorings", "test_moorings", "moorings"),
    SuiteSpec("clearance", "test_clearance", "clearance"),
    SuiteSpec("standoff", "test_standoff", "standoff berths"),
    SuiteSpec("freeflight", "test_freeflight", "free flight"),
    SuiteSpec("byhand", "test_byhand", "flying by hand"),
    SuiteSpec("showflying", "test_showflying", "showing the flying"),
    SuiteSpec("fog", "test_fog", "fog"),
    SuiteSpec("conn", "test_conn", "conn"),
    SuiteSpec("position", "test_position", "ship position"),
    SuiteSpec("cameras", "test_cameras", "cameras"),
    SuiteSpec("reticle", "test_reticle", "reticle"),
    SuiteSpec("connwindow", "test_connwindow", "conn window"),
    SuiteSpec("worlds", "test_worlds", "worlds"),
    SuiteSpec("surfaces", "test_surfaces", "surfaces"),
    SuiteSpec("projection", "test_projection", "projection"),
    SuiteSpec("drawbudget", "test_drawbudget", "draw budget"),
    SuiteSpec("starlight", "test_starlight", "starlight"),
    SuiteSpec("hullshapes", "test_hullshapes", "hull shapes"),
    SuiteSpec("catalogue", "test_catalogue", "catalogue"),
    SuiteSpec("silhouettes", "test_silhouettes", "silhouettes"),
    SuiteSpec("works3d", "test_works3d", "station structures"),
    SuiteSpec("robots", "test_robots", "machines"),
    SuiteSpec("robots3d", "test_robots3d", "machine bodies"),
    SuiteSpec("bay", "test_bay", "internal bays"),
    SuiteSpec("control", "test_control", "approach control"),
    SuiteSpec("forcing", "test_forcing", "forcing a berth"),
    SuiteSpec("interdiction", "test_interdiction", "interdiction"),
    SuiteSpec("life3d", "test_life3d", "xenoform bodies"),
    SuiteSpec("parts3d", "test_parts3d", "fitting pictures"),
    SuiteSpec("relics3d", "test_relics3d", "relic pictures"),
    SuiteSpec("skykit", "test_sky_kit", "sky kit"),
    SuiteSpec("lighting", "test_lighting", "lighting"),
    SuiteSpec("orbits", "test_orbits", "orbits"),
    SuiteSpec("programmes", "test_programmes", "programmes"),
    SuiteSpec("exchequer", "test_exchequer", "exchequer"),
    SuiteSpec("industry", "test_industry", "industry"),
    SuiteSpec("declared", "test_declared", "declared"),
    SuiteSpec("revived", "test_revived", "revived"),
    SuiteSpec("screening", "test_screening", "screening"),
    SuiteSpec("lopsided", "test_lopsided", "lopsided"),
    SuiteSpec("pilot", "test_pilot", "pilot"),
    SuiteSpec("berthing", "test_berthing", "berthing"),
    SuiteSpec("thrusters", "test_thrusters", "thrusters"),
    SuiteSpec("weave", "test_weave", "weave"),
    SuiteSpec("customs", "test_customs", "customs"),
    SuiteSpec("allegiance", "test_allegiance", "allegiance"),
    SuiteSpec("public", "test_public", "public"),
    SuiteSpec("territory", "test_territory", "territory"),
    SuiteSpec("charts", "test_charts", "charts"),
    SuiteSpec("aftermath", "test_aftermath", "aftermath"),
    SuiteSpec("notes", "test_notes", "notes"),
    SuiteSpec("layers", "test_layers", "layers"),
    SuiteSpec("cargo", "test_cargo", "cargo"),
    SuiteSpec("freight", "test_freight", "freight"),
    SuiteSpec("workings", "test_workings", "workings"),
    SuiteSpec("burns", "test_burns", "burns"),
    SuiteSpec("bench", "test_bench", "bench"),
    SuiteSpec("works", "test_works", "works"),
    SuiteSpec("overtures", "test_overtures", "overtures"),
    SuiteSpec("seats", "test_seats", "seats"),
    SuiteSpec("founding", "test_founding", "founding"),
    SuiteSpec("attempts", "test_attempts", "attempts"),
    SuiteSpec("reach", "test_reach", "reach"),
    SuiteSpec("plans", "test_plans", "plans"),
    SuiteSpec("beginnings", "test_beginnings", "beginnings"),
    SuiteSpec("legacy", "test_legacy", "legacy"),
    SuiteSpec("instruments", "test_instruments", "instruments"),
    SuiteSpec("voices", "test_voices", "voices"),
    SuiteSpec("bridge", "test_bridge", "bridge"),
    SuiteSpec("time", "test_time", "time"),
    SuiteSpec("anchorage", "test_anchorage", "anchorage"),
    SuiteSpec("traffic", "test_traffic", "traffic"),
    SuiteSpec("doctrine", "test_doctrine", "doctrine"),
    SuiteSpec("firing", "test_firing", "firing"),
    SuiteSpec("approach", "test_approach", "approach"),
    SuiteSpec("officials", "test_officials", "officials"),
    SuiteSpec("dormancy", "test_dormancy", "dormancy"),
    SuiteSpec("tuning", "test_tuning", "tuning"),
    SuiteSpec("hands", "test_hands", "hands"),
    SuiteSpec("approaching", "test_approach_game", "approaching"),
    SuiteSpec("harness", "test_harness_guard", "harness"),
    SuiteSpec("salvage", "test_salvage", "salvage"),
    SuiteSpec("provisional", "test_provisional", "provisional"),
    SuiteSpec("counter", "test_counter", "counter"),
    SuiteSpec("wharfage", "test_wharfage", "wharfage"),
    SuiteSpec("climbs", "test_climbs", "climbs"),
    SuiteSpec("company", "test_company", "company"),
    SuiteSpec("parley", "test_parley", "parley"),
    SuiteSpec("wayhome", "test_wayhome", "wayhome"),
    SuiteSpec("abilities", "test_abilities", "abilities"),
    SuiteSpec("levy", "test_levy", "levy"),
    SuiteSpec("accord", "test_accord", "accord"),
    SuiteSpec("landing", "test_landing", "landing"),
    SuiteSpec("setdown", "test_setdown", "coming down"),
    SuiteSpec("charting", "test_charting", "charting"),
    SuiteSpec("conviction", "test_conviction", "conviction"),
    SuiteSpec("evidence", "test_bench_kinds", "evidence"),
    SuiteSpec("envoy", "test_envoy", "envoy"),
    SuiteSpec("seatwork", "test_seatwork", "seatwork"),
    SuiteSpec("thermal_doors", "test_thermal_doors", "thermal doors"),
    SuiteSpec("ventures", "test_ventures", "ventures"),
    SuiteSpec("orderplan", "test_orderplan", "order plan"),
    SuiteSpec("turnplan", "test_turnplan", "turn plan"),
    SuiteSpec("postings", "test_postings", "postings"),
    SuiteSpec("grants", "test_grants", "grants"),
    SuiteSpec("helm", "test_helm", "helm"),
    SuiteSpec("thermal", "test_thermal", "thermal"),
    SuiteSpec("courting", "test_courting", "courting"),
    SuiteSpec("picture", "test_picture", "picture"),
    SuiteSpec("seams", "test_seams", "seams"),
    SuiteSpec("manual", "test_manual", "manual"),
    SuiteSpec("tutorial", "test_tutorial", "tutorial"),
    SuiteSpec("grudges", "test_grudges", "grudges"),
    SuiteSpec("gunnery", "test_gunnery", "gunnery"),
    SuiteSpec("volley", "test_volley", "volley"),
    SuiteSpec("gunboard", "test_gunboard", "gunboard"),
    SuiteSpec("readiness", "test_readiness", "readiness"),
    SuiteSpec("gunfire", "test_gunfire", "gunfire"),
    SuiteSpec("surveys", "test_surveys", "surveys"),
    SuiteSpec("chronicle", "test_chronicle", "chronicle", True),
    SuiteSpec("dig", "test_dig", "dig"),
    SuiteSpec("resume", "test_resume", "resume", True),
    SuiteSpec("verbs", "test_verbs", "verbs", True),
    SuiteSpec("ui", "test_ui", "interface", True),
]

SUITES_BY_KEY = {s.key: s for s in SUITES}

#: Order matters: this is the order a full run reports in.
ALL_SUITES = [s.key for s in SUITES]
